operator_weights = {
    "CollectLimit": 1,
    "Scan hive": 5,
    "Filter": 2,
    "Project": 1,
    "Sort": 3,
    "Aggregate": 4,
    "Window": 5,
    "Union": 2,
    "Repartition": 3,
    "Subquery": 3,
    "MapJoin": 3,
    "BroadcastHashJoin": 5,
    "ShuffleHashJoin": 5,
    "SortMergeJoin": 5,
    "Exchange": 4,
    "BroadcastExchange": 4,
    "AdaptiveSparkPlan": 0,
    "ReusedExchange": 2,
    "DeserializeToObject": 1,
    "SerializeFromObject": 1,
    "WholeStageCodegen": 0,
    "InMemoryRelation": 3,
    "HashPartitioning": 2,
    "RangePartitioning": 2,
    "GlobalLimit": 1,
    "LocalLimit": 1,
    "SubqueryAlias": 0,
    "CommandResult": 1
}
